### ISSUE TITLE
Paper is published? Where is the code :-)

### ISSUE THREAD

**Issue by tomuench** [look-whos-talking-chatbots/hyleca#1]
Dear Team,

i stumbled above your paper HyLECA and want to have a look at your sources. Can you publish them? 

Bests, Tobias

**Comment by ErkanBasar** [comment]
Thank you for your interest and reaching out! It is right that the paper is already published. We have had the ambition to publish the code with a complete and extensive documentation with a more robust implementation. Given that we are a small team, this ambition kept delaying us.

The code is made public now as-is! We hope that this is already helpful. We are going to update it with a fully documented version as soon as we achieve our goal. Apologies for the delay from everyone who was interested in our software.
